### PR TITLE
Update Evo 4 Readme

### PR DESCRIPTION
**Pull request by andyrichardson**
## Changes

 - Update driver link
 - Remove notice about bug with mic 1 (not an issue)
 - Add config for loopback with DAW and Amp Sim

### CODE REVIEW

**Comment by mdias** [comment]
Thanks for the contribution!
I think you forgot to remove one `My RS_ASIO.ini` entry from there, it now has 3 and I think you only meant to have 2, can you please check before I merge?

**Comment by andyrichardson** [comment]
@mdias yeah you're right - just fixed it

**Comment by AmolAmrit** [comment]
I just wrote my guide right now and end me seeing this :P

**Comment by mdias** [comment]
Looks good! Merged

**Pull request merged**
