### PR TITLE
I have tested Roland ua55 and it is working perfectly

### PR DESCRIPTION
**Pull request by bugparty**
Thanks for the software, it is great!
besides, is there some book or documents on asio driver or how to read the program source code?

### CODE REVIEW

**Comment by mdias** [comment]
Hello, no problem, hope you're enjoying it :)

I see a couple of simple things that need to be fixed improved:

1. In the docs file you created both config files are using the same input channel, and I think this is not what you meant.
2. Also in the docs file, your second example "If plugging in input 2" is using an old style config file; which even though it will work, we should update it to the latest style like you use in the 1st example.
3. Can you please add a link to this document also in the interface name you added in the main README file?

Thank you for contributing 👍

**Comment by mdias** [comment]
Also, regarding your question about documents on ASIO driver and this program's source; for ASIO you can download their SDK and look into their documentation, and for this program, the big important parts of it are just implementing the Wasapi APIs on top of ASIO, so if you look up on MSDN for Wasapi documentation for the relevant interfaces used (like IAudioClient and so on) you should be able to get a general idea.

**Comment by bugparty** [comment]
Thanks for telling me the ASIO and Wasapi

> In the docs file you created both config files are using the same input channel, and I think this is not what you meant.

Sorry, the config file I wrote is not what I mean, I will modify it. what I mean is:
the roland ua55 have two input, so what I want to say is, if We use the default settings and do not block one of the input, RockSmith will let you to disable one.

> Can you please add a link to this document also in the interface name you added in the main README file?

I will add a link, I was in a hurry, sorry.

**Comment by mdias** [comment]
It's ok, no need to rush :)

**Comment by bugparty** [comment]
I have updated

**Comment by mdias** [comment]
Thanks, merged! :)

**Pull request merged**
