### PR TITLE
Add Audient Evo 4 to README

### LINKED ISSUE #84: Audient Evo 4 Feedback
## About

Hey there, I was able to get the [Audient Evo 4](https://evo.audio/products/evo-4/overview/) to work with rs_asio (on Windows). 

Maybe this guide is useful for anyone with the same interface. Also, it's another device to add the compatibility list in the README 👐

P.S. Thanks for the awesome work on this project ❤️ 

### Get drivers

Install the latest [official driver](https://audient.com/products/audio-interfaces/sono/downloads/) (v4.0.9 currently).

### Set asio control panel settings

Use a DAW such as [Reaper](https://www.reaper.fm/) to open the asio control panel for the Evo 4.

image

There isn't actually any panel but you should see an `e` logo in your taskbar. Right click it and set the sample rate to 48KHz. 

> Note: if you don't do this, you will see an error when Rocksmith opens stating there is no output device detected.

### Setup RS_ASIO

Follow the [configuration guide](https://github.com/mdias/rs_asio#basic-configuration-guide) and set desired outputs and inputs to `Audient USB Audio ASIO Driver`.

If you're using the interface for input, **only the second input seems to be working**. Not too sure why this is but you'll need to set the channel of your input to `1` and use the second TRS input.

#### Config files

<details>
<summary>My RS_ASIO.ini</summary>

```
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=Audient USB Audio ASIO Driver
BaseChannel=0
EnableSoftwareEndpointVolumeControl=0
EnableSoftwareMasterVolumeControl=0
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=Audient USB Audio ASIO Driver
Channel=1
EnableSoftwareEndpointVolumeControl=0
EnableSoftwareMasterVolumeControl=0
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
```

</details>

<details>
<summary>My Rocksmith.ini</summary>

```
[Audio]
EnableMicrophone=1
ExclusiveMode=1
LatencyBuffer=2
ForceDefaultPlaybackDevice=
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=
RealToneCableOnly=0
Win32UltraLowLatencyMode=1
[Renderer.Win32]
ShowGamepadUI=0
ScreenWidth=2560
ScreenHeight=1440
Fullscreen=0
VisualQuality=2
RenderingWidth=0
RenderingHeight=0
EnablePostEffects=1
EnableShadows=1
EnableHighResScope=1
EnableDepthOfField=1
EnablePerPixelLighting=1
MsaaSamples=4
DisableBrowser=0
[Net]
UseProxy=1
```

</details>

### PR DESCRIPTION
**Pull request by andyrichardson**
## About

Add Audient Evo 4 to README. 

Fix #84

### CODE REVIEW

**Comment by mdias** [comment]
This looks good, but I want to ask you if you mind if I copy paste the instructions in #84 into the documentation folder, or if you'd rather do it yourself as part of this merge; if so, I'll wait, otherwise I'll merge and commit the documentation afterwards.

**Comment by andyrichardson** [comment]
Thanks @mdias!

I'll open a PR tomorrow morning

**Comment by andyrichardson** [comment]
@mdias I've moved things over to the docs. 

Feel free to change whatever you need before merging :+1:

**Comment by mdias** [comment]
Looks perfect, merged! Thank you for the contribution 👍

**Pull request merged**
