### PR TITLE
Add UMC404HD

### PR DESCRIPTION
**Pull request by orivej**
UMC404HD config is probably applicable to UMC204HD too, but the link refers to UMC404HD.

### CODE REVIEW

**Comment by mdias** [comment]
Indeed, I have the 204HD and it's applicable.
Can I ask you to instead of renaming the entry create another one? If you don't have time let me know and I'll merge this one and do it myself :)

**Comment by orivej** [comment]
Done.

Have you considered adding optimal LatencyBuffer values to the readme? (UMC404HD has no issues with LatencyBuffer=1.)

**Comment by mdias** [comment]
I don't know exactly what kind of adverse effect LatencyBuffer can have, so that could end up creating problems on some users.

**Comment by mdias** [comment]
Also, thank you for the contribution :)

**Pull request merged**
