### PR TITLE
evo 4: Update guide for RS_ASIO

### PR DESCRIPTION
**Pull request by AmolAmrit**
* It is the best method to use Rocksmith if you don't own their patent cable and want to use your Audient EVO 4 interface

### CODE REVIEW

**Comment by AmolAmrit** [comment]
Although you can remove the images from the folder or update the link.

**Comment by mdias** [comment]
You'll need to rebase as this now conflicts with the latest changes from the other PR :)

**Comment by AmolAmrit** [comment]
@mdias Done!

**Comment by mdias** [comment]
done! thank you for the contribution 👍

**Comment by SAARussian** [comment]
Game just crash, when I launch it with EVO 4

**Comment by Phantatsy** [comment]
RS_ASIO also works on the Audient EVO 16 using the standard settings. User confirmed working with 128 buffer size.

**Comment by mdias** [comment]
> RS_ASIO also works on the Audient EVO 16 using the same settings as the EVO 4. User confirmed working with 128 buffer size.

Thank you for the report. Added to the list 👍

**Pull request merged**
